# .streamlit/secrets.toml

[connections.snowflake]
account = "XK25145.JLAVALAWSWEST"
user = "TCROSSLINAWSWEST"
password = "@ThunderGinny2910"
role = "SYSADMIN"
warehouse = "WORKER1"
database = "HCLS_COERTEX_DEMO_DB"
schema = "SETUP"
