# .streamlit/secrets.toml

[connections.snowflake]
account = "XK25145-JLAVALAWSWEST"
user = "TCROSSLINAWSWEST"
password = 
role = "SYSADMIN"
warehouse = "WORKER1"
database = "HCLS_COERTEX_DEMO_DB"
schema = "SETUP"
